name: CI - Test and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432  # Use standard Postgres port

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Wait for Postgres to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for Postgres..."
          sleep 5
        done

    - name: Run Migrations
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: python manage.py migrate

    - name: Run Tests
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t django-ci-cd .

    - name: Verify Docker container
      run: docker run -d -p 8072:8072 django-ci-cd && sleep 10 && docker ps -a

    - name: Stop and Remove Docker Container
      run: |
        CONTAINER_ID=$(docker ps -aqf "name=django-ci-cd")
        if [ -n "$CONTAINER_ID" ]; then
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
        else
          echo "No container found with the name 'django-ci-cd'."
        fi
